control:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/control_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/control_db
    username: postgres
    password: postgres