server:
  port: 8083

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5435/auth_db
    username: postgres
    password: postgres

    kafka:
      bootstrap-servers: localhost:9092

      consumer:
        group-id: saas-group
        auto-offset-reset: earliest


  jpa:
    show-sql: true

  spring:
    flyway:
      enabled: true
