server:
  port: 8085

spring:
  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/control_db
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    consumer:
      group-id: order-group
      auto-offset-reset: earliest