server:
  port: 8082

spring:
  application:
    name: product-service
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/control_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

control:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/control_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG